-- VoidScoutHistory.lua — auto-generated by build_history.py
-- DO NOT EDIT — regenerate via: python build_history.py

VoidScoutHistory = VoidScoutHistory or {}

VoidScoutHistory["Acindish-Stormrage-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=50, Activity=80, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=65, Activity=100, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=70, Activity=100, Survival=0, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=70, Activity=90, Survival=0, Teamwork=50 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=58, Activity=89, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Aimedjupiter-Area52-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=35, Interrupts=0, Activity=85, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=60, Interrupts=0, Activity=90, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=65, Activity=100, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=95, Activity=100, Survival=0, Teamwork=75 } },
  },
}

VoidScoutHistory["Akanthør-Quel'Thalas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=85, Interrupts=0, Activity=40, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=95, Interrupts=0, Activity=60, Survival=100, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=90, Interrupts=0, Activity=55, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=75, Interrupts=0, Activity=55, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=90, Activity=50, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=85, Activity=70, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=80, Activity=55, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=90, Activity=60, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=90, Activity=55, Survival=0, Teamwork=80 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=100, Activity=55, Survival=0, Teamwork=80 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=80, Activity=50, Survival=0, Teamwork=80 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=65, Activity=50, Survival=0, Teamwork=85 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=84, Activity=53, Survival=0, Teamwork=95 } },
  },
}

VoidScoutHistory["Alïm-Sargeras-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=20, Activity=15, Survival=100, Teamwork=100 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=15, Interrupts=0, Activity=5, Survival=0, Teamwork=100 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=10, Interrupts=0, Activity=10, Survival=100, Teamwork=100 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=15, Interrupts=0, Activity=15, Survival=100, Teamwork=100 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=15, Interrupts=0, Activity=15, Survival=100, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=10, Activity=5, Survival=100, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=15, Activity=5, Survival=0, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=20, Activity=15, Survival=100, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=15, Activity=15, Survival=100, Teamwork=100 } },
  },
}

VoidScoutHistory["Angrycows-Darkspear-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=38, Interrupts=0, Activity=31, Survival=0, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=23, Activity=23, Survival=0, Teamwork=38 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=23, Activity=23, Survival=0, Teamwork=38 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=23, Activity=23, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=15, Activity=8, Survival=0, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=23, Interrupts=0, Activity=23, Survival=0, Teamwork=77 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=69, Activity=85, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=23, Interrupts=0, Activity=31, Survival=100, Teamwork=77 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=62, Activity=38, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=23, Activity=23, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=31, Activity=23, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=23, Activity=15, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=15, Activity=8, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=23, Activity=23, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=23, Interrupts=0, Activity=23, Survival=0, Teamwork=31 } },
  },
}

VoidScoutHistory["Arayia-Gilneas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=92, Interrupts=0, Activity=69, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=85, Activity=77, Survival=100, Teamwork=38 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=100, Activity=85, Survival=100, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=85, Interrupts=0, Activity=54, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=85, Interrupts=0, Activity=62, Survival=100, Teamwork=85 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=69, Interrupts=0, Activity=69, Survival=0, Teamwork=46 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=46, Activity=46, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=85, Interrupts=0, Activity=62, Survival=100, Teamwork=38 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=85, Activity=54, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=62, Activity=46, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=85, Interrupts=0, Activity=54, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=85, Interrupts=0, Activity=62, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=92, Interrupts=0, Activity=62, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=85, Interrupts=0, Activity=62, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=85, Interrupts=0, Activity=62, Survival=0, Teamwork=92 } },
  },
}

VoidScoutHistory["Avocatto-Proudmoore-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=54, Interrupts=0, Activity=46, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=38, Activity=38, Survival=0, Teamwork=69 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=69, Activity=54, Survival=100, Teamwork=62 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=62, Interrupts=0, Activity=62, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=62, Interrupts=0, Activity=54, Survival=100, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=54, Interrupts=0, Activity=46, Survival=0, Teamwork=46 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=62, Activity=62, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=69, Interrupts=0, Activity=69, Survival=100, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=54, Activity=62, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=31, Activity=31, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=77, Interrupts=0, Activity=69, Survival=0, Teamwork=62 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=54, Activity=38, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=62, Interrupts=0, Activity=54, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=54, Interrupts=0, Activity=38, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=54, Interrupts=0, Activity=46, Survival=0, Teamwork=54 } },
  },
}

VoidScoutHistory["Blowjov-Proudmoore-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=80, Interrupts=0, Activity=100, Survival=0, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=75, Interrupts=0, Activity=95, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=85, Interrupts=0, Activity=100, Survival=100, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=85, Interrupts=11, Activity=100, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=90, Interrupts=0, Activity=100, Survival=100, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=80, Activity=95, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=90, Activity=95, Survival=0, Teamwork=60 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=90, Activity=100, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=75, Activity=100, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=95, Activity=100, Survival=0, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=85, Activity=95, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=90, Activity=95, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=80, Activity=95, Survival=100, Teamwork=75 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=95, Activity=95, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Breadbearer-Sargeras-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=100, Interrupts=0, Activity=80, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=65, Interrupts=0, Activity=85, Survival=0, Teamwork=80 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=60, Interrupts=0, Activity=80, Survival=0, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=70, Interrupts=20, Activity=80, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=70, Interrupts=20, Activity=80, Survival=100, Teamwork=70 } },
  },
}

VoidScoutHistory["Chaxe-MoonGuard-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=95, Activity=65, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=100, Activity=70, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=100, Activity=65, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=95, Activity=65, Survival=0, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=100, Activity=65, Survival=0, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=90, Activity=60, Survival=100, Teamwork=90 } },
  },
}

VoidScoutHistory["Elkratos-MoonGuard-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=30, Activity=35, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Felonytank-Proudmoore-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=45, Activity=45, Survival=0, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=40, Activity=30, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=35, Activity=35, Survival=100, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=45, Interrupts=0, Activity=35, Survival=100, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=40, Interrupts=0, Activity=35, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=40, Activity=30, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=35, Activity=35, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=45, Activity=30, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=60, Activity=40, Survival=0, Teamwork=25 } },
  },
}

VoidScoutHistory["Finreck-Illidan-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=60, Interrupts=0, Activity=40, Survival=0, Teamwork=80 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=65, Interrupts=20, Activity=40, Survival=100, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=85, Activity=70, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=70, Activity=60, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=60, Activity=50, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=80, Activity=75, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=45, Activity=30, Survival=0, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=75, Activity=60, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=60, Activity=55, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=40, Activity=35, Survival=0, Teamwork=50 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=79, Activity=58, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Florence-Gilneas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=23, Interrupts=0, Activity=23, Survival=100, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=31, Activity=31, Survival=100, Teamwork=85 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=31, Activity=31, Survival=100, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=31, Interrupts=0, Activity=31, Survival=0, Teamwork=92 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=31, Interrupts=0, Activity=31, Survival=100, Teamwork=85 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=46, Interrupts=0, Activity=38, Survival=0, Teamwork=85 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=46, Activity=46, Survival=0, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=46, Interrupts=0, Activity=23, Survival=100, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=38, Activity=31, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=38, Activity=38, Survival=100, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=23, Interrupts=0, Activity=31, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=31, Interrupts=5, Activity=31, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=31, Interrupts=0, Activity=31, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=31, Interrupts=20, Activity=31, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=31, Interrupts=0, Activity=31, Survival=0, Teamwork=92 } },
  },
}

VoidScoutHistory["Flyingfrög-Sargeras-US"] = {
  fights = {
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=68, Activity=68, Survival=0, Teamwork=89 } },
  },
}

VoidScoutHistory["Frogbob-Azralon-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=30, Interrupts=0, Activity=60, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=30, Activity=55, Survival=0, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=30, Interrupts=0, Activity=50, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=30, Interrupts=13, Activity=65, Survival=100, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=30, Activity=60, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=40, Activity=75, Survival=0, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=30, Activity=60, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=30, Activity=65, Survival=100, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=35, Activity=60, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=35, Activity=50, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=25, Activity=45, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=25, Activity=65, Survival=100, Teamwork=50 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=26, Activity=47, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Gglolxd-Mal'Ganis-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=85, Activity=40, Survival=0, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=90, Activity=40, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=45, Activity=20, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=100, Activity=40, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Gjuice-EmeraldDream-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=100, Interrupts=0, Activity=45, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=100, Interrupts=0, Activity=70, Survival=100, Teamwork=70 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=100, Interrupts=0, Activity=60, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=100, Interrupts=0, Activity=60, Survival=100, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=100, Activity=75, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=100, Activity=80, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=100, Activity=75, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=95, Activity=80, Survival=0, Teamwork=50 } },
  },
}

VoidScoutHistory["Jamer-Gilneas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=62, Interrupts=0, Activity=54, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=62, Activity=46, Survival=100, Teamwork=100 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=54, Activity=38, Survival=100, Teamwork=100 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=54, Interrupts=0, Activity=38, Survival=0, Teamwork=100 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=54, Interrupts=0, Activity=38, Survival=100, Teamwork=100 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=77, Interrupts=0, Activity=62, Survival=0, Teamwork=100 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=100, Activity=92, Survival=100, Teamwork=100 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=54, Interrupts=0, Activity=46, Survival=100, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=69, Activity=77, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=69, Activity=69, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=54, Interrupts=2, Activity=62, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=62, Interrupts=3, Activity=69, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=77, Interrupts=5, Activity=77, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=62, Interrupts=9, Activity=54, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=62, Activity=54, Survival=0, Teamwork=54 } },
  },
}

VoidScoutHistory["Klefthoof-Kael'thas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=10, Activity=10, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Krolack-Stormrage-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=70, Activity=45, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=20, Activity=20, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=70, Activity=40, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=55, Activity=35, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=40, Activity=75, Survival=0, Teamwork=20 } },
  },
}

VoidScoutHistory["Kujahh-Area52-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=85, Activity=85, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Latana-Arthas-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=70, Activity=85, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=50, Activity=80, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=50, Activity=85, Survival=0, Teamwork=15 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=45, Activity=80, Survival=0, Teamwork=15 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=63, Activity=74, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Lusze-Area52-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=15, Activity=8, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=15, Activity=8, Survival=100, Teamwork=69 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=15, Activity=15, Survival=100, Teamwork=62 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=15, Activity=8, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=8, Activity=15, Survival=100, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=15, Activity=8, Survival=0, Teamwork=77 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=54, Activity=54, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=15, Activity=8, Survival=100, Teamwork=77 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=8, Activity=8, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=15, Activity=15, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=15, Activity=8, Survival=0, Teamwork=62 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=15, Activity=8, Survival=0, Teamwork=62 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=23, Activity=15, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=15, Activity=8, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=15, Activity=15, Survival=0, Teamwork=92 } },
  },
}

VoidScoutHistory["Madrona-Gilneas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=85, Interrupts=33, Activity=77, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=69, Activity=62, Survival=100, Teamwork=38 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=62, Activity=62, Survival=100, Teamwork=38 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=92, Interrupts=0, Activity=92, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=92, Interrupts=1, Activity=77, Survival=100, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=85, Interrupts=25, Activity=85, Survival=0, Teamwork=46 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=46, Activity=46, Survival=0, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=77, Interrupts=0, Activity=85, Survival=100, Teamwork=38 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=92, Activity=92, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=100, Activity=85, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=92, Interrupts=4, Activity=85, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=92, Interrupts=5, Activity=92, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=85, Activity=38, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=92, Interrupts=6, Activity=77, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=92, Interrupts=4, Activity=77, Survival=0, Teamwork=31 } },
  },
}

VoidScoutHistory["Miikazukys-Quel'Thalas-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=40, Interrupts=0, Activity=30, Survival=0, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=65, Interrupts=0, Activity=30, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=50, Interrupts=0, Activity=30, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=45, Activity=35, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=75, Activity=55, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=50, Activity=35, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=50, Activity=30, Survival=0, Teamwork=25 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=65, Activity=50, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=45, Activity=35, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=65, Activity=40, Survival=0, Teamwork=15 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=60, Activity=45, Survival=100, Teamwork=15 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=53, Activity=26, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Misclickr-Tichondrius-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=35, Interrupts=0, Activity=25, Survival=0, Teamwork=95 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=25, Interrupts=0, Activity=25, Survival=0, Teamwork=95 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=25, Interrupts=67, Activity=25, Survival=100, Teamwork=95 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=25, Interrupts=25, Activity=25, Survival=100, Teamwork=95 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=25, Interrupts=50, Activity=25, Survival=100, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=25, Activity=25, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=50, Activity=40, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=25, Activity=25, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=25, Activity=25, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=30, Activity=35, Survival=0, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=25, Activity=25, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=30, Activity=30, Survival=0, Teamwork=100 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=35, Activity=25, Survival=100, Teamwork=100 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=32, Activity=37, Survival=0, Teamwork=89 } },
  },
}

VoidScoutHistory["Mknirvanna-Ragnaros-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=40, Activity=60, Survival=0, Teamwork=85 } },
  },
}

VoidScoutHistory["Nathaanis-Bonechewer-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=55, Activity=45, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=55, Activity=45, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=75, Activity=60, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=55, Activity=55, Survival=0, Teamwork=20 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=42, Activity=42, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Niÿ-Azralon-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=5, Activity=10, Survival=0, Teamwork=90 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=5, Activity=5, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=5, Activity=10, Survival=100, Teamwork=80 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=10, Activity=10, Survival=100, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=5, Activity=15, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=5, Activity=10, Survival=0, Teamwork=60 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=10, Activity=10, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=5, Activity=10, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=5, Activity=10, Survival=0, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=10, Activity=10, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=5, Activity=5, Survival=0, Teamwork=35 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=5, Activity=10, Survival=100, Teamwork=50 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=5, Activity=5, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Panconping-Mannoroth-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=10, Activity=10, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Renjad-WyrmrestAccord-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=8, Activity=15, Survival=100, Teamwork=92 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=8, Activity=15, Survival=100, Teamwork=85 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=8, Activity=8, Survival=100, Teamwork=85 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=8, Interrupts=0, Activity=15, Survival=0, Teamwork=92 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=23, Interrupts=0, Activity=23, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=8, Interrupts=0, Activity=15, Survival=0, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=46, Activity=46, Survival=0, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=8, Interrupts=0, Activity=15, Survival=100, Teamwork=77 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=15, Activity=23, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=15, Activity=15, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=8, Interrupts=0, Activity=15, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=8, Activity=23, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=8, Interrupts=0, Activity=23, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=8, Activity=15, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=8, Activity=8, Survival=0, Teamwork=92 } },
  },
}

VoidScoutHistory["Rènza-Maiev-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=55, Interrupts=0, Activity=65, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=50, Interrupts=0, Activity=65, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=75, Interrupts=0, Activity=65, Survival=0, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=55, Interrupts=0, Activity=65, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=45, Interrupts=0, Activity=45, Survival=0, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=35, Activity=40, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=30, Activity=30, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=35, Activity=45, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=40, Activity=45, Survival=0, Teamwork=25 } },
  },
}

VoidScoutHistory["Sainsei-LaughingSkull-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=31, Interrupts=0, Activity=62, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=46, Activity=92, Survival=100, Teamwork=69 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=38, Activity=77, Survival=100, Teamwork=100 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=46, Interrupts=0, Activity=69, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=46, Interrupts=0, Activity=69, Survival=100, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=31, Interrupts=0, Activity=54, Survival=0, Teamwork=46 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=92, Activity=100, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=31, Interrupts=0, Activity=54, Survival=0, Teamwork=38 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=31, Activity=69, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=54, Activity=77, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=46, Interrupts=0, Activity=77, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=46, Interrupts=0, Activity=77, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=38, Interrupts=3, Activity=85, Survival=0, Teamwork=85 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=46, Interrupts=13, Activity=85, Survival=0, Teamwork=54 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=46, Interrupts=3, Activity=85, Survival=0, Teamwork=62 } },
  },
}

VoidScoutHistory["Sardonic-Frostmourne-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=65, Interrupts=0, Activity=55, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=60, Interrupts=0, Activity=50, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=80, Interrupts=0, Activity=50, Survival=0, Teamwork=70 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=75, Interrupts=0, Activity=45, Survival=0, Teamwork=90 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=80, Interrupts=0, Activity=50, Survival=100, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=60, Activity=55, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=55, Activity=45, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=75, Activity=70, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=70, Activity=50, Survival=0, Teamwork=75 } },
  },
}

VoidScoutHistory["Scind-Stormrage-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=95, Activity=50, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Shadowuser-Area52-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=70, Interrupts=0, Activity=70, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=90, Interrupts=33, Activity=70, Survival=0, Teamwork=65 } },
  },
}

VoidScoutHistory["Shamkat-Zul'jin-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=46, Interrupts=100, Activity=38, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=54, Activity=54, Survival=100, Teamwork=38 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=46, Activity=46, Survival=100, Teamwork=38 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=38, Interrupts=0, Activity=46, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=38, Interrupts=0, Activity=46, Survival=100, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=38, Interrupts=0, Activity=31, Survival=0, Teamwork=46 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=85, Activity=77, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=38, Interrupts=0, Activity=38, Survival=100, Teamwork=38 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=46, Activity=46, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=46, Activity=54, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=38, Interrupts=0, Activity=38, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=38, Interrupts=3, Activity=46, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=46, Interrupts=10, Activity=69, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=38, Interrupts=0, Activity=46, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=38, Interrupts=0, Activity=38, Survival=0, Teamwork=31 } },
  },
}

VoidScoutHistory["Skallagrímur-Azralon-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=50, Activity=30, Survival=0, Teamwork=85 } },
  },
}

VoidScoutHistory["Skorn-Nemesis-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=70, Interrupts=0, Activity=55, Survival=0, Teamwork=80 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=55, Interrupts=0, Activity=45, Survival=100, Teamwork=70 } },
  },
}

VoidScoutHistory["Slimzilla-Icecrown-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=75, Activity=95, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=70, Activity=90, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=35, Activity=80, Survival=0, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=85, Activity=100, Survival=100, Teamwork=50 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=74, Activity=100, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Striikes-Azgalor-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=15, Activity=20, Survival=100, Teamwork=90 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=10, Activity=15, Survival=0, Teamwork=80 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=15, Activity=15, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=10, Activity=5, Survival=100, Teamwork=90 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=5, Interrupts=0, Activity=5, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=15, Activity=10, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=10, Activity=15, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=5, Activity=5, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=10, Activity=5, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=10, Activity=5, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=5, Activity=5, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=10, Activity=10, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=10, Activity=5, Survival=100, Teamwork=65 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=16, Activity=11, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Stunlockholm-Frostmourne-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=35, Interrupts=100, Activity=80, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=45, Interrupts=0, Activity=85, Survival=100, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=40, Interrupts=0, Activity=75, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=35, Interrupts=0, Activity=70, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=55, Activity=65, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=45, Activity=50, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=55, Activity=80, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=35, Activity=55, Survival=0, Teamwork=25 } },
  },
}

VoidScoutHistory["Supbae-Mal'Ganis-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=75, Interrupts=100, Activity=75, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=80, Interrupts=0, Activity=75, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=70, Interrupts=33, Activity=75, Survival=100, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=80, Interrupts=22, Activity=70, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=85, Interrupts=10, Activity=75, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=75, Activity=80, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=60, Activity=65, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=85, Activity=85, Survival=100, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=85, Activity=85, Survival=0, Teamwork=25 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=80, Activity=70, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=60, Activity=75, Survival=0, Teamwork=20 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=85, Activity=75, Survival=0, Teamwork=15 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=75, Activity=75, Survival=100, Teamwork=15 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=89, Activity=79, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Tulao-Feathermoon-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=100, Interrupts=0, Activity=92, Survival=100, Teamwork=92 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=100, Activity=69, Survival=100, Teamwork=69 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=92, Activity=69, Survival=100, Teamwork=62 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=100, Interrupts=0, Activity=85, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=100, Interrupts=0, Activity=92, Survival=100, Teamwork=69 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=100, Interrupts=0, Activity=92, Survival=0, Teamwork=77 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=77, Activity=69, Survival=100, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=100, Interrupts=0, Activity=92, Survival=100, Teamwork=77 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=100, Activity=85, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=92, Activity=92, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=100, Interrupts=0, Activity=92, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=100, Interrupts=3, Activity=85, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=100, Interrupts=0, Activity=92, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=100, Interrupts=0, Activity=92, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=100, Interrupts=10, Activity=92, Survival=0, Teamwork=54 } },
  },
}

VoidScoutHistory["Vantwing-Ragnaros-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=25, Activity=40, Survival=100, Teamwork=85 } },
  },
}

VoidScoutHistory["Vede-Elune-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=60, Interrupts=0, Activity=95, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=45, Interrupts=0, Activity=100, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=50, Interrupts=0, Activity=95, Survival=100, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=50, Interrupts=11, Activity=95, Survival=0, Teamwork=40 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=55, Interrupts=0, Activity=95, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=50, Activity=90, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=65, Activity=90, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=40, Activity=95, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=45, Activity=95, Survival=0, Teamwork=80 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=60, Activity=90, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=40, Activity=85, Survival=0, Teamwork=80 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=55, Activity=90, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=50, Activity=85, Survival=100, Teamwork=50 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=47, Activity=84, Survival=0, Teamwork=68 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=77, Interrupts=0, Activity=100, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=92, Activity=100, Survival=100, Teamwork=100 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=77, Activity=100, Survival=100, Teamwork=38 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=77, Interrupts=0, Activity=100, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=69, Interrupts=0, Activity=100, Survival=0, Teamwork=69 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=92, Interrupts=0, Activity=100, Survival=0, Teamwork=77 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=46, Activity=46, Survival=0, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=92, Interrupts=0, Activity=100, Survival=100, Teamwork=77 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=77, Activity=100, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=77, Activity=100, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=69, Interrupts=0, Activity=100, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=77, Interrupts=0, Activity=100, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=69, Interrupts=0, Activity=100, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=69, Interrupts=0, Activity=100, Survival=0, Teamwork=100 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=69, Interrupts=0, Activity=100, Survival=0, Teamwork=100 } },
  },
}

VoidScoutHistory["Veredelyse-Darkspear-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=15, outcome="kill", duration=187, axes={ Damage=69, Interrupts=33, Activity=85, Survival=100, Teamwork=77 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=15, outcome="kill", duration=299, axes={ Damage=77, Activity=85, Survival=0, Teamwork=38 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=15, outcome="kill", duration=268, axes={ Damage=85, Activity=92, Survival=100, Teamwork=38 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="wipe", duration=127, axes={ Damage=69, Interrupts=5, Activity=77, Survival=0, Teamwork=77 } },
    { encounter_id=3178, encounter_name="Vaelgor & Ezzorak", difficulty_id=15, outcome="kill", duration=396, axes={ Damage=77, Interrupts=4, Activity=85, Survival=100, Teamwork=54 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=328, axes={ Damage=62, Interrupts=33, Activity=77, Survival=0, Teamwork=46 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="wipe", duration=16, axes={ Damage=46, Activity=46, Survival=0, Teamwork=92 } },
    { encounter_id=3180, encounter_name="Lightblinded Vanguard", difficulty_id=15, outcome="kill", duration=263, axes={ Damage=62, Interrupts=33, Activity=77, Survival=100, Teamwork=38 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=109, axes={ Damage=23, Activity=15, Survival=0, Teamwork=69 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=163, axes={ Damage=85, Activity=62, Survival=0, Teamwork=92 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=297, axes={ Damage=62, Interrupts=0, Activity=46, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=276, axes={ Damage=69, Interrupts=0, Activity=54, Survival=0, Teamwork=62 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=282, axes={ Damage=54, Interrupts=6, Activity=46, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=472, axes={ Damage=77, Interrupts=0, Activity=69, Survival=0, Teamwork=46 } },
    { encounter_id=3181, encounter_name="Crown of the Cosmos", difficulty_id=15, outcome="wipe", duration=523, axes={ Damage=77, Interrupts=0, Activity=69, Survival=0, Teamwork=31 } },
  },
}

VoidScoutHistory["Vintyui-Area52-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=15, Activity=20, Survival=0, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=20, Activity=20, Survival=0, Teamwork=95 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=20, Activity=25, Survival=0, Teamwork=90 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=15, Activity=20, Survival=100, Teamwork=95 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=21, Activity=21, Survival=0, Teamwork=100 } },
  },
}

VoidScoutHistory["Wrathvi-Mal'Ganis-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=25, Activity=25, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=30, Activity=30, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=40, Activity=35, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=30, Activity=30, Survival=100, Teamwork=75 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=37, Activity=32, Survival=0, Teamwork=89 } },
  },
}

VoidScoutHistory["Zãl-Stormrage-US"] = {
  fights = {
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=80, Activity=70, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=95, Activity=70, Survival=0, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=95, Activity=70, Survival=100, Teamwork=65 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=100, Activity=63, Survival=0, Teamwork=68 } },
  },
}

VoidScoutHistory["Zòx-Area52-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=95, axes={ Damage=90, Activity=90, Survival=100, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=95, Interrupts=0, Activity=90, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=90, Interrupts=0, Activity=90, Survival=0, Teamwork=55 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=95, Interrupts=0, Activity=90, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=95, Interrupts=0, Activity=85, Survival=100, Teamwork=45 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=95, Activity=85, Survival=0, Teamwork=50 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=80, Activity=85, Survival=0, Teamwork=60 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=65, Activity=90, Survival=0, Teamwork=40 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=65, Activity=90, Survival=0, Teamwork=75 } },
  },
}

VoidScoutHistory["Ártëmisä-Sargeras-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=20, Activity=20, Survival=0, Teamwork=85 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=20, Activity=20, Survival=0, Teamwork=90 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=365, axes={ Damage=20, Activity=20, Survival=100, Teamwork=80 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="kill", duration=379, axes={ Damage=20, Activity=20, Survival=100, Teamwork=85 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=125, axes={ Damage=20, Activity=20, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=376, axes={ Damage=25, Activity=25, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=124, axes={ Damage=15, Activity=20, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=276, axes={ Damage=20, Activity=20, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=374, axes={ Damage=20, Activity=15, Survival=0, Teamwork=75 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=136, axes={ Damage=15, Activity=15, Survival=0, Teamwork=70 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="wipe", duration=290, axes={ Damage=15, Activity=15, Survival=0, Teamwork=55 } },
    { encounter_id=3177, encounter_name="Vorasius", difficulty_id=16, outcome="kill", duration=366, axes={ Damage=20, Activity=15, Survival=0, Teamwork=65 } },
    { encounter_id=3179, encounter_name="Fallen-King Salhadaar", difficulty_id=16, outcome="wipe", duration=48, axes={ Damage=11, Activity=16, Survival=0, Teamwork=89 } },
  },
}

VoidScoutHistory["Ängëlä-Ragnaros-US"] = {
  fights = {
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=55, Interrupts=0, Activity=35, Survival=0, Teamwork=65 } },
    { encounter_id=3176, encounter_name="Imperator Averzian", difficulty_id=16, outcome="wipe", duration=254, axes={ Damage=65, Activity=40, Survival=100, Teamwork=55 } },
  },
}
